@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzc4MDIxODc4LCJleHAiOjE3NzgwNTA2Nzh9.pM1vOrCIFZtiZoEyL_SeD4flhH4EFDUuWkSco9VG9_g

POST http://localhost:3000/api/posts
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Zé mané",
    "content":"Test",
    "userId": 1
}

###

GET http://localhost:3000/api/posts

###

PUT http://localhost:3000/api/posts/3
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Zé manéee",
    "content":"Test"
}

###

DELETE http://localhost:3000/api/posts/2
Authorization: Bearer {{authToken}}