@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzc3NTkxNzU0LCJleHAiOjE3Nzc2MjA1NTR9.WGSXFWlfKtP8kJWvioN0kjhuPGNumNAdFyTGc9y_02I

POST http://localhost:3000/api/posts
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Zé mané",
    "content":"Test",
    "userId": 1
}

###

GET http://localhost:3000/api/posts

###

PUT http://localhost:3000/api/posts/1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title": "Zé mané",
    "content":"Test"
}

###

DELETE http://localhost:3000/api/posts/1