@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzc4MDIxODc4LCJleHAiOjE3NzgwNTA2Nzh9.pM1vOrCIFZtiZoEyL_SeD4flhH4EFDUuWkSco9VG9_g
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "firstName": "Zeca",
    "lastName": "maluco",
    "email": "zeca.maluco@email.com",
    "phone": "24994142909",
    "role": "user",
    "password": "aluno1234"
}

###

GET http://localhost:3000/api/users

###

DELETE http://localhost:3000/api/users

###

PATCH http://localhost:3000/api/users
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "firstName": "Zecão",
    "lastName": "malucão",
    "email": "zeca.maluco@emailu.com"
}

###

PATCH http://localhost:3000/api/users/2/toggle

###

GET http://localhost:3000/api/users/active

###

PATCH  http://localhost:3000/api/users/role/2
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "role": "admin"
}

###

