POST http://localhost:3000/api/users
Content-Type: application/json

{
    "firstName": "Zeca",
    "lastName": "maluco",
    "email": "zeca.maluco@emaily.com",
    "phone": "24994142909",
    "password": "aluno1234"
}

###

GET http://localhost:3000/api/users

###

DELETE http://localhost:3000/api/users/6

###

PATCH http://localhost:3000/api/users/1
Content-Type: application/json

{
    "firstName": "Zecão",
    "lastName": "malucão",
    "email": "zeca.maluco@emailw.com"
}

###

PATCH http://localhost:3000/api/users/11/toggle

###

GET http://localhost:3000/api/users/active

###

